serviceAccount:
  create: true
webui:
  service:
    type: ClusterIP
    port: 443
  ingress:
    enabled: enabled
    certManager: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    rules:
      - host: crafty.do.krinchan.com 
        paths:
          - "/"
    tls:
      - secretName: crafty-tls
        hosts:
          - crafty.do.krinchan.com
minecrafts:
  - name: primary-server
    service:
      type: LoadBalancer
      ports:
        - name: gameserver
          port: 25565
          targetPort: 25565
          protocol: TCP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: minecraft.do.krinchan.com
        service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"
        service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "25565"
        service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
persistence:
  db:
    enabled: true
    storageClassName: "nfs"
    storageSize: 1Gi
    accessModes:
      - ReadWriteMany
  servers:
    enabled: true
    storageClassName: "nfs"
    storageSize: 1Gi
    accessModes:
      - ReadWriteMany
  backups:
    enabled: enabled
    storageClassName: "nfs"
    storageSize: 1Gi
    accessModes:
      - ReadWriteMany
