apiVersion: v1
kind: Service
metadata:
  name: {{ include "crafty-control-mc.fullname" . }}
  labels:
    {{- include "crafty-control-mc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "crafty-control-mc.selectorLabels" . | nindent 4 }}
