name: Lint and Test Charts
on:
  pull_request:
    paths:
      - 'charts/**'
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Chart Testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Lint Chart
        run: ct lint --config .github/ct.yaml
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run helm-docs
        run: docker run -v "$GITHUB_WORKSPACE:/helm-docs" jnorwood/helm-docs:latest
      - name: Check diffs
        run: git diff --exit-code
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.17.17
          - v1.18.15
          - v1.19.7
          - v1.20.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Chart Testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@master
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Install Charts
        run: ct install --config .github/ct.yaml
